spring.application.name=educacion
spring.datasource.url=jdbc:mysql://localhost:3306/plataforma_educativa
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# Configuración de JWT (Clave segura de más de 32 caracteres)
jwt.secret=esta_es_una_clave_secreta_super_larga_y_segura_de_mas_de_32_caracteres_para_la_plataforma
jwt.expiration=86400000